# fly.toml app configuration file generated for zikor-be on 2024-01-25T14:46:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zikor-be'
primary_region = 'lhr'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION= 'pgsql'
  DB_HOST= 'zikor-db.flycast'
  DB_PORT= '5432'
  DB_DATABASE= 'zikor-be'
  DB_USERNAME= 'postgres'
  


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = '30s'
  interval = '15s'
  method = 'GET'
  timeout = '5s'
  path = '/'

[deploy]
 # strategy = 'bluegreen'
 release_command = 'php artisan migrate --force'

[mounts]
 source='storage_dir'
 destination='/var/www/html/storage'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

